/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistUserIndexRouteImport } from './routes/regist-user/index'
import { Route as MiningmapIndexRouteImport } from './routes/miningmap/index'
import { Route as HistoriesIndexRouteImport } from './routes/histories/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistUserIndexRoute = RegistUserIndexRouteImport.update({
  id: '/regist-user/',
  path: '/regist-user/',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningmapIndexRoute = MiningmapIndexRouteImport.update({
  id: '/miningmap/',
  path: '/miningmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriesIndexRoute = HistoriesIndexRouteImport.update({
  id: '/histories/',
  path: '/histories/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/histories': typeof HistoriesIndexRoute
  '/miningmap': typeof MiningmapIndexRoute
  '/regist-user': typeof RegistUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/histories': typeof HistoriesIndexRoute
  '/miningmap': typeof MiningmapIndexRoute
  '/regist-user': typeof RegistUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/histories/': typeof HistoriesIndexRoute
  '/miningmap/': typeof MiningmapIndexRoute
  '/regist-user/': typeof RegistUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/histories' | '/miningmap' | '/regist-user'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/histories' | '/miningmap' | '/regist-user'
  id: '__root__' | '/' | '/histories/' | '/miningmap/' | '/regist-user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriesIndexRoute: typeof HistoriesIndexRoute
  MiningmapIndexRoute: typeof MiningmapIndexRoute
  RegistUserIndexRoute: typeof RegistUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regist-user/': {
      id: '/regist-user/'
      path: '/regist-user'
      fullPath: '/regist-user'
      preLoaderRoute: typeof RegistUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miningmap/': {
      id: '/miningmap/'
      path: '/miningmap'
      fullPath: '/miningmap'
      preLoaderRoute: typeof MiningmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/histories/': {
      id: '/histories/'
      path: '/histories'
      fullPath: '/histories'
      preLoaderRoute: typeof HistoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriesIndexRoute: HistoriesIndexRoute,
  MiningmapIndexRoute: MiningmapIndexRoute,
  RegistUserIndexRoute: RegistUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
