services:
  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-controller
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - MONGO_USER=unifi
      - MONGO_PASS=unifi_password
      - MONGO_HOST=unifi-mongo
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024
      - MONGO_TLS=false
      - MONGO_AUTHSOURCE=admin
    volumes:
      - unifi-data:/config
    ports:
      - "8443:8443"
      - "8082:8080"
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "1900:1900/udp"
      - "8843:8843"
      - "8880:8880"
      - "6789:6789"
    networks:
      - unifi-net
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: unifi-mongo
    security_opt:
      - apparmor:unconfined
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=unifi
      - MONGO_INITDB_ROOT_PASSWORD=unifi_password
    volumes:
      - mongo-data:/data/db
    networks:
      - unifi-net

volumes:
  mongo-data:
  unifi-data:

networks:
  unifi-net:
    driver: bridge
